name: AWS AMI using Packer Config



on:

  pull_request:

    branches: [ main ]

  workflow_dispatch:



jobs:

  packer:

    runs-on: ubuntu-latest

    permissions:

      id-token: write

      contents: read

    name: AMI Creation.

    steps:

      - name: Check Repository

        uses: actions/checkout@v2

      - name: Configure Credentials

        uses: aws-actions/configure-aws-credentials@v1

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: us-east-1


      - name: Packer Init

        working-directory: .

        run: packer init 


      - name: Validate PAcker Template

        working-directory: .

        run: packer validate amiFinal.pkr.hcl


      - name: Start AMI

        working-directory: .

        run: packer build --var-file=amiFinal.pkrvars.hcl amiFinal.pkr.hcl