name: AWS AMI using Packer Config



on:

  push:

    branches: [ main ]

  workflow_dispatch:



jobs:

  packer:

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}

    runs-on: ubuntu-latest

    permissions:

      id-token: write

      contents: read

    name: AMI Creation.

    steps:

      - name: Check Repository

        uses: actions/checkout@v2


      - name: Zip all the webapp imp files
        run: |
          zip -r webapp.zip ./
          pwd ./webapp


      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        

      - name: Start AMI

        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: amiFinal.pkr.hcl
 
        
