name: AMI

on:


  pull_request:


    branches: [ main ]



  workflow_dispatch:




jobs:


  deploy:


    runs-on: ubuntu-latest


    strategy:

        matrix:

            node-version: [16.x]


    steps:

      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v1

        with:

            node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run build --if-present

      - run: npm test
      - name: AWS Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      - name: Packer running

        working-directory: ./
      - run: packer init 

      - name: Packer Validate
      - run: packer validate -syntax-only -var-file="amiFinal.pkrvars.hcl" amiFinal.pkr.hcl


      - name: Building AMI
        working-directory: ./
      - run: packer build -var-file="amiFinal.pkrvars.hcl" amiFinal.pkr.hcl
      
        
      
